Revert "ts: Add ts-ignore-error TS6133 to ignore unused imports."
Don't work, because it can't be applied to the whole file. Only for the next line.

This reverts commit 3a832966e7fc6130ad12285c54aec619d6f2dbcd.